apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-ingress
  namespace: api
  annotations:
    networking.gke.io/managed-certificates: "ruaymak99.com-tls-cert"
    kubernetes.io/ingress.global-static-ip-name: "ingress-webapps"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/user
        pathType: Prefix
        backend:
          service:
            name: api-user-service
            port:
              number: 443     
      - path: /api/v1/wallet
        pathType: Prefix
        backend:
          service:
            name: api-wallet-service
            port:
              number: 443     
      - path: /api/testV1
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 443    
      - path: /api/testV2
        pathType: Prefix
        backend:
          service:
            name: api-2-service
            port:
              number: 443                          
      # - path: /api/v1/user/create
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: api-user-service
      #       port:
      #         number: 443     
      # - path: /api/v1/user/delete
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: api-user-service
      #       port:
      #         number: 443  
      # - path: /api/v1/user/update
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: api-user-service
      #       port:
      #         number: 443  